; ============================================
; Slave STM32 - Bridge Vibration Monitor v3.2
; MPU6050 + FFT + LoRa (change SLAVE_ID in config.h)
; ============================================

[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = arduino
monitor_speed = 115200
upload_protocol = stlink
debug_tool = stlink

lib_deps =
    sandeepmistry/LoRa @ ^0.8.0
