; ============================================
; Master ESP32 - Bridge Vibration Monitor v3.0
; Thu nhận dữ liệu từ 3 Slave qua LoRa
; Web Dashboard + WiFi AP+STA
; ============================================

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = default.csv
lib_deps =
    sandeepmistry/LoRa @ ^0.8.0
    me-no-dev/ESPAsyncWebServer @ ^1.2.3
    me-no-dev/AsyncTCP @ ^1.1.1
