; ============================================
; Master ESP32 - Bridge Vibration Monitor v3.2
; Polls 2 Slaves via LoRa, Web Dashboard
; ============================================

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = default.csv
lib_deps =
    sandeepmistry/LoRa @ ^0.8.0
    me-no-dev/ESPAsyncWebServer @ ^1.2.3
    me-no-dev/AsyncTCP @ ^1.1.1
